name: Publish Firefox Extension

on:
  release:
    types: [created]

permissions:
  contents: write  

jobs:
  build-sign-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js and jq
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install web-ext and jq
      run: |
        npm install --global web-ext
        sudo apt-get update && sudo apt-get install -y jq

    - name: Build extension
      run: web-ext build --artifacts-dir ./web-ext-artifacts

    - name: Sign extension
      run: |
        web-ext sign \
          --api-key="${{ secrets.FIREFOX_JWT_ISSUER }}" \
          --api-secret="${{ secrets.FIREFOX_JWT_SECRET }}" \
          --artifacts-dir ./web-ext-artifacts \
          --channel=listed \
          --source-dir .

    - name: Extract version from manifest
      id: get_version
      run: |
        VERSION=$(jq -r '.version' manifest.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Rename signed extension
      run: |
        mkdir -p final-artifacts
        cp web-ext-artifacts/*.xpi final-artifacts/inertia-devtools-v${{ env.VERSION }}.xpi

    - name: Upload signed extension as release asset
      uses: softprops/action-gh-release@v2
      with:
        files: final-artifacts/*.xpi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}