name: Publish Firefox Extension

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-sign-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js and web-ext
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install web-ext
      run: npm install --global web-ext

    - name: Sign extension
      run: |
        web-ext sign \
          --api-key="${{ secrets.FIREFOX_JWT_ISSUER }}" \
          --api-secret="${{ secrets.FIREFOX_JWT_SECRET }}" \
          --channel=listed \
          --source-dir . \
          --artifacts-dir ./signed-artifacts \
          --amo-metadata=./amo-metadata.json

    - name: Upload signed extension as release asset
      uses: softprops/action-gh-release@v2
      with:
        files: signed-artifacts/*.xpi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
